### ISSUE TITLE
Add Pause on Hover and Swipe Feature

### ISSUE THREAD

**Issue by amirahad** [asif-jalil/scroll-carousel-react#1]
**Feature Request:**
I would like to propose the addition of a "pause on hover" and "swipe" feature to the Scroll Carousel npm package. Currently, the carousel scrolls automatically, but it would be great to give users more control and interactivity.

**Pause on Hover:**

-     Description: When a user hovers their cursor over the carousel, it should pause scrolling to allow them to interact with the content.
-     Benefit: This feature would improve the user experience by preventing automatic scrolling when users want to focus on specific items.

**Swipe Feature:**

-     Description: Implement swipe gestures to allow users on touch-enabled devices to swipe left or right to navigate through the carousel.
-     Benefit: This would make the carousel more accessible and user-friendly for mobile and tablet users.

**Comment by asif-jalil** [comment]
Thanks for your great suggestion.

**Pause on hover** is really great and will improve user experience. If you want you can develope this feature and make a pull request. Otherwise i will do that as soon as possible when i manage time to contribute.

**Swipe** This is also a great feature for carousel. But i think this feature is not properly aligned with scroll carousel concept. This feature will loose the defination of scroll carousel. So there is no plan to make this feature.

**Comment by amirahad** [comment]
i'll try to develop the feature once i get free.
